version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password@123
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"  # Optional, for local development
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Optional, for local development
    networks:
      - my-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Optional, for local development
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasks
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password@123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - my-network

networks:
  my-network: